# --- Definiciones Reutilizables ---
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-limits: &default-limits
  deploy:
    resources:
      limits:
        cpus: '1'
        memory: 1G

services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    logging: *default-logging
    <<: *default-limits
    ports:
      # --- Puertos Públicos ---
      - '80:80'    # HTTP
      - '443:443'  # HTTPS
      - '127.0.0.1:81:81'
      # --- Puerto de Admin ---
      # ¡PELIGRO! No exponer a internet. Ver README.md
      # - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ../backend/static:/var/www/convertidor/static
    networks:
      - proxy-global
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  proxy-global:
    external: true