cat > .github/workflows/deploy-docker.yml << 'EOF'
name: Deploy to VPS with Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DEPLOY_PATH: /var/www/Convertidor

jobs:
  deploy:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v4
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: 📥 Install Node dependencies
        run: npm ci
      
      - name: 🎨 Build Tailwind CSS
        run: npm run build:css
      
      - name: 🔐 Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      
      - name: 💾 Create backup on server
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            if [ -d ${{ env.DEPLOY_PATH }} ]; then
              timestamp=$(date +%Y%m%d_%H%M%S)
              echo "📦 Creating backup..."
              tar -czf /tmp/convertidor_backup_${timestamp}.tar.gz \
                --exclude='node_modules' \
                --exclude='__pycache__' \
                --exclude='.git' \
                ${{ env.DEPLOY_PATH }} 2>/dev/null || true
              echo "✅ Backup created: /tmp/convertidor_backup_${timestamp}.tar.gz"
              
              # Mantener solo los últimos 5 backups
              ls -t /tmp/convertidor_backup_*.tar.gz | tail -n +6 | xargs -r rm
            fi
          EOF
      
      - name: 📤 Sync files to server
        run: |
          rsync -avz --progress --delete \
            --exclude 'node_modules' \
            --exclude '__pycache__' \
            --exclude '.git' \
            --exclude '.env' \
            --exclude '*.pyc' \
            --exclude '*.log' \
            --exclude '.DS_Store' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ env.DEPLOY_PATH }}/
      
      - name: 🐳 Deploy with Docker Compose
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd ${{ env.DEPLOY_PATH }}
            
            echo "📂 Directorio actual: $(pwd)"
            
            # Verificar que .env existe
            if [ ! -f .env ]; then
              echo "❌ Error: .env file not found"
              echo "Por favor configura el archivo .env en el servidor"
              exit 1
            fi
            
            # Cargar variables del .env
            source .env
            
            # Detener contenedores actuales
            echo "🛑 Deteniendo contenedores..."
            docker-compose down || true
            
            # Construir imágenes
            echo "🏗️  Construyendo imágenes..."
            docker-compose build --no-cache
            
            # Levantar servicios
            echo "🚀 Iniciando servicios..."
            docker-compose up -d
            
            # Esperar a que MySQL esté listo
            echo "⏳ Esperando a que MySQL esté listo..."
            sleep 15
            
            # Verificar que los contenedores estén corriendo
            if ! docker-compose ps | grep -q "Up"; then
              echo "❌ Error: Los contenedores no se levantaron correctamente"
              docker-compose logs
              exit 1
            fi
            
            # Crear usuario admin si es la primera vez
            echo "👤 Verificando usuario admin..."
            ADMIN_EXISTS=$(docker-compose exec -T db mysql -u root -p${MYSQL_ROOT_PASSWORD} zafiro_bi -se "SELECT COUNT(*) FROM usuarios WHERE usuario='admin'" 2>/dev/null || echo "0")
            
            if [ "$ADMIN_EXISTS" = "0" ]; then
              echo "📝 Creando usuario admin..."
              ADMIN_HASH=$(docker-compose exec -T backend python3 -c "from werkzeug.security import generate_password_hash; print(generate_password_hash('${ADMIN_PASSWORD:-admin123}'))" | tr -d '\r\n')
              
              docker-compose exec -T db mysql -u root -p${MYSQL_ROOT_PASSWORD} zafiro_bi <<EOSQL
              INSERT INTO usuarios (usuario, password, rol) VALUES ('admin', '${ADMIN_HASH}', 'admin');
EOSQL
              echo "✅ Usuario admin creado"
            else
              echo "ℹ️  Usuario admin ya existe"
            fi
            
            # Mostrar estado
            echo ""
            echo "📊 Estado de los contenedores:"
            docker-compose ps
            echo ""
          EOF
      
      - name: 🔍 Health Check
        run: |
          echo "⏳ Esperando que la aplicación esté lista..."
          sleep 10
          
          # Probar puerto 8080 (contenedor Docker)
          response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.VPS_HOST }}:8080/ 2>/dev/null || echo "000")
          
          if [ "$response" = "200" ] || [ "$response" = "302" ] || [ "$response" = "301" ]; then
            echo "✅ Aplicación respondiendo correctamente (HTTP $response)"
          else
            echo "⚠️  Advertencia: La aplicación respondió con HTTP $response"
            echo "Esto puede ser normal si tienes Nginx externo configurado"
          fi
      
      - name: 📊 Deployment Summary
        if: always()
        run: |
          echo ""
          echo "======================================"
          echo "  🎉 Deploy Completado"
          echo "======================================"
          echo ""
          echo "📝 Información:"
          echo "  • Proyecto: Convertidor"
          echo "  • Branch: ${{ github.ref_name }}"
          echo "  • Commit: ${{ github.sha }}"
          echo "  • Autor: ${{ github.actor }}"
          echo ""
          echo "🔗 URLs:"
          echo "  • Contenedor directo: http://${{ secrets.VPS_HOST }}:8080"
          echo "  • Con Nginx externo: http://convertidor.synapzys.com"
          echo ""
          echo "📋 Comandos útiles:"
          echo "  • Ver logs:     ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd ${{ env.DEPLOY_PATH }} && docker-compose logs -f'"
          echo "  • Ver estado:   ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd ${{ env.DEPLOY_PATH }} && docker-compose ps'"
          echo "  • Reiniciar:    ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd ${{ env.DEPLOY_PATH }} && docker-compose restart'"
          echo ""
EOF
